In [13]:
import torch

a = torch.tensor([[1], [2]])

print(a)

a.repeat(4, 1).reshape(2, 4)

tensor([[1],
        [2]])


tensor([[1, 2, 1, 2],
        [1, 2, 1, 2]])

In [19]:
a = torch.tensor([1 + 2j])
a.T

tensor([1.+2.j])